import { redirect } from "next/navigation";
import { eq } from "drizzle-orm";

import { auth } from "@/auth";
import { db } from "@/lib/db";
import { recommendations } from "@/drizzle/schema";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export default async function RecommendationsPage() {
  const session = await auth();

  if (!session?.user?.id) {
    redirect("/login");
  }

  const userRecommendations = await db.query.recommendations.findMany({
    where: eq(recommendations.userId, session.user.id),
    orderBy: (table, { desc }) => [desc(table.createdAt)],
  });

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold">AI Recommendations</h1>

        <p className="text-muted-foreground">
          Personalized suggestions generated by AI to help you improve your
          habits and stay consistent.
        </p>
      </div>

      {userRecommendations.length === 0 ? (
        <Card>
          <CardContent className="py-10 text-center">
            <h2 className="text-xl font-semibold">No Recommendations Yet</h2>

            <p className="mt-2 text-muted-foreground">
              Continue completing habits and your AI coach will generate
              personalized recommendations.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-6 lg:grid-cols-2">
          {userRecommendations.map((recommendation) => (
            <Card key={recommendation.id}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>{recommendation.title}</CardTitle>

                  <Badge>{recommendation.priority}</Badge>
                </div>

                <CardDescription className="capitalize">
                  {recommendation.type}
                </CardDescription>
              </CardHeader>

              <CardContent className="space-y-4">
                <p className="leading-7 text-muted-foreground">
                  {recommendation.description}
                </p>

                <div className="text-xs text-muted-foreground">
                  Created {recommendation.createdAt.toLocaleDateString()}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
